from i_hr_data_hierarchy_manager import IHRDataHierarchyManager
from i_hr_hierarchy_data_getter import IHRHierarchyDataGetter
from i_hr_soldier_data_manager import IHRSoldiersDataManager
from i_hr_soldiers_data_getter import IHRSoldierDataGetter